### ISSUE TITLE
guidance required

### ISSUE THREAD

**Issue by jpoyser** [Thomas2500/go-fitbit#1]
Not really an issue but I'm hoping to use this package for a research project I'm working on with multiple fitbit accounts and just trying to get the intraday data down. I have managed to do this manually using postman but would love to be able to use this to automate the process.
 
I have two questions I'm not sure on regarding the initial auth access process (and please excuse my ignorance and silly question)

1. If I have http://localhost in my app settings will that matter even if it returns a 404 as I've used this process to establish a access token (rather cumbersome though)
2. I notice in the code it's looking for a token.json file. What should be in this file?

Kind Regards

Justin

**Comment by hawkesn** [comment]
Might be a bit late for you @jpoyser, but here are some quick steps:
1. Create your app via `dev.fitbit.com/new` and fill out junk details for local development:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/1168175/188252582-b54948c5-352c-47ef-9516-2a8ff6ee2aa0.png">

The only thing that matters here is the `http://localhost:48558` for local development that matches the server port.

2. Hit save and the app will be registered, the easy thing is to follow the tutorial link: 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1168175/188252640-290cae22-1b09-49ca-939f-b546a2645e87.png">

3. In the tutorial, step 1, change it to: "Authorization Code Flow"
4. Press the generated authorization link and complete the prompts
5. Enter the code and it will generate a `curl` command, put that into your terminal and the result is the `token.json` you're looking for. Save that locally in the same directory in `example/server`
6. From there, run `go run .` and then browse to `127.0.0.1/48558` to see the example website. Hope that helps
