### ISSUE TITLE
Is this auto generated?

### ISSUE THREAD

**Issue by gregstarr** [Thomas2500/go-fitbit#17]
Hello,

Is this library auto generated from the swagger json? 

Thanks

**Comment by Thomas2500** [comment]
Hi @gregstarr!
No, the swagger documentation isn't correct at multiple parts which would make it incompatible with the real API.

**Comment by gregstarr** [comment]
darn. I had started to work on autogenerated code here: https://github.com/gregstarr/gfit/tree/main

I did notice some discrepancies between the website and the swagger doc. On top of that, none of the return types are documented in the swagger json, only on the website and it seemed like a pain to scrape. 

I will most likely abandon my repo and just use yours from now on

**Comment by Thomas2500** [comment]
Let me know if you're missing something in my repo that needs to be added.
